# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75960d936de056e8e9f621dc47958648401d1e452c71ccbf039ee1ed7a16b3b297c4cdeaf48cc8fedbdfe74ad3e58db3da70cc4dabb0a6f6aba9ef3c0187e5ba

test:
  secret_key_base: a6667ce0a0a021e259374330fb4ece2aa971ea1de5871a4c383c01aabb294b2f826e3ccef6712cfff3c332ecc352bc67c9c81cc85cd82a053e79e7a6e75a6def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
